version: '2'
services:
    glusterfns:
       image: fabriziogaliano/gluster2nfs:latest

       container_name: gluster2nfs

       privileged: true

       environment:
          GLUSTER_VOLUMES: 'vol01 vol02'
          GLUSTER_HOST: glusterhost01.local.domain

       extra_hosts:
          - glusterhost01.local.domain:192.168.0.5
          - glusterhost02.local.domain:192.168.0.10
     
       ports:
          - "2049:2049"

       restart: always
